### PR TITLE
Add JSON output `index.json`.

### PR DESCRIPTION
**Pull request by AdamHillier**
I thought I could get away with parsing RSS, but it doesn't include links to images, which I need. So instead here's a very lightweight `index.json` template.

### CODE REVIEW

**Comment by AdamHillier** [comment]
Huh, `hugo --gc` doesn't throw on my machine 🤔

**Comment by AdamHillier** [comment]
@lgeiger could you test this branch locally?

**Comment by lgeiger** [comment]
Hmm this seems to work for me locally as well. I am on hugo v0.82.0

**Comment by AdamHillier** [comment]
> Hmm this seems to work for me locally as well. I am on hugo v0.82.0

Yes, likewise :+1:

**Comment by lgeiger** [comment]
Looks like vercel still uses v0.58.2, I'll checkout if I can change this.

**Comment by AdamHillier** [comment]
Ah brilliant, thanks <3

And now it works: https://blog-5d8a7dzya-plumerai.vercel.app/index.json

**Review by lgeiger — APPROVED** [review]

**Pull request merged**
